apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dhepdtjfb-go 
  janus-idp.io/tekton: dhepdtjfb-go
  backstage.io/kubernetes-id: dhepdtjfb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dhepdtjfb-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml