apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dhepdtjfb-go-gitops
  description: This is GitOps manifest for dhepdtjfb-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=dhepdtjfb-go
    backstage.io/kubernetes-id: dhepdtjfb-go 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: dhepdtjfb-go-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:dhepdtjfb-go
